DROP DATABASE BirdieDB;
CREATE DATABASE BirdieDB;
USE BirdieDB;
-- Create Tables

CREATE TABLE Ball
(
	ID INT NOT NULL IDENTITY PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	ColourID INT NOT NULL
);

CREATE TABLE Colour
(
	ID INT NOT NULL IDENTITY PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

-- Foreign Keys

ALTER TABLE Ball
ADD FOREIGN KEY (ColourID) REFERENCES Colour(ID);

-- Add Colours

INSERT INTO Colour VALUES ('Black');
INSERT INTO Colour VALUES ('White');
INSERT INTO Colour VALUES ('Red');
INSERT INTO Colour VALUES ('Blue');
INSERT INTO Colour VALUES ('Yellow');
INSERT INTO Colour VALUES ('Orange');
INSERT INTO Colour VALUES ('Purple');
INSERT INTO Colour VALUES ('Green');
INSERT INTO Colour VALUES ('Brown');
INSERT INTO Colour VALUES ('Pink');

TRUNCATE TABLE Ball;

INSERT INTO Ball VAlUES ('FunSports 1', 8);
INSERT INTO Ball VAlUES ('FunSports 2', 10);
INSERT INTO Ball VAlUES ('FunSports 3', 1);
INSERT INTO Ball VAlUES ('FunSports 4', 3);
INSERT INTO Ball VAlUES ('FunSports 5', 8);
INSERT INTO Ball VAlUES ('FunSports 6', 7);
INSERT INTO Ball VAlUES ('FunSports 7', 5);
INSERT INTO Ball VAlUES ('FunSports 8', 4);



